In [35]:
import numpy as np
import pandas as pd
import matplotlib as mpl

In [36]:
cijfers = np.loadtxt('cijfers.csv')
cijfers

array([[ 6.5,  7.3,  6.4],
       [ 8. ,  8. ,  8.5],
       [ 3.2,  4. ,  5. ],
       [ 7.9,  7.1,  3.5],
       [ 7.3,  7.8,  8. ],
       [ 8.6,  8. ,  9. ],
       [ 4. ,  6. ,  5.5],
       [ 7.3,  7.8,  7.8],
       [ 4.5,  5.6,  7.7],
       [ 5. ,  7. ,  7.2]])

In [37]:
cijfers.size

30

In [38]:
cijfers.ndim

2

In [39]:
cijfers.shape

(10, 3)

In [40]:
cijfers.dtype

dtype('float64')

In [41]:
cijfers[2][1] = 4.3
cijfers

array([[ 6.5,  7.3,  6.4],
       [ 8. ,  8. ,  8.5],
       [ 3.2,  4.3,  5. ],
       [ 7.9,  7.1,  3.5],
       [ 7.3,  7.8,  8. ],
       [ 8.6,  8. ,  9. ],
       [ 4. ,  6. ,  5.5],
       [ 7.3,  7.8,  7.8],
       [ 4.5,  5.6,  7.7],
       [ 5. ,  7. ,  7.2]])

In [42]:
cijfers.min()

3.2000000000000002

In [43]:
cijfers.max()

9.0

In [44]:
cijfers.mean()

6.6599999999999993

In [45]:
for vak in range(cijfers.shape[1]):
    print(cijfers[:, vak].mean())

6.23
6.89
6.86


In [46]:
cijfers >= 5

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False,  True],
       [ True,  True, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [48]:
cijfers

array([[ 6.5,  7.3,  6.4],
       [ 8. ,  8. ,  8.5],
       [ 3.2,  4.3,  5. ],
       [ 7.9,  7.1,  3.5],
       [ 7.3,  7.8,  8. ],
       [ 8.6,  8. ,  9. ],
       [ 4. ,  6. ,  5.5],
       [ 7.3,  7.8,  7.8],
       [ 4.5,  5.6,  7.7],
       [ 5. ,  7. ,  7.2]])

In [51]:
cijfers2 = pd.read_table('cijfers.csv', sep=" ", header=None)

In [53]:
cijfers2.dtypes

0    float64
1    float64
2    float64
dtype: object

In [55]:
cijfers2.mean()

0    6.23
1    6.86
2    6.86
dtype: float64

In [61]:
cijfers2.describe()

0          1          2
count  10.000000  10.000000  10.000000
mean    6.230000   6.860000   6.860000
std     1.902075   1.297176   1.734743
min     3.200000   4.000000   3.500000
25%     4.625000   6.250000   5.725000
50%     6.900000   7.200000   7.450000
75%     7.750000   7.800000   7.950000
max     8.600000   8.000000   9.000000

In [63]:
cijfers2["new"] = 1

In [64]:
cijfers2

0    1    2  new
0  6.5  7.3  6.4    1
1  8.0  8.0  8.5    1
2  3.2  4.0  5.0    1
3  7.9  7.1  3.5    1
4  7.3  7.8  8.0    1
5  8.6  8.0  9.0    1
6  4.0  6.0  5.5    1
7  7.3  7.8  7.8    1
8  4.5  5.6  7.7    1
9  5.0  7.0  7.2    1

In [65]:
cijfers2.drop("new", axis=1)

0    1    2
0  6.5  7.3  6.4
1  8.0  8.0  8.5
2  3.2  4.0  5.0
3  7.9  7.1  3.5
4  7.3  7.8  8.0
5  8.6  8.0  9.0
6  4.0  6.0  5.5
7  7.3  7.8  7.8
8  4.5  5.6  7.7
9  5.0  7.0  7.2